### PR TITLE
Added user stories for assigned issues

### PR DESCRIPTION
**Pull request by himi98**
Hi Team, 
I have appended the user stories associated with the issues #6 and #12  in the [user_stories_Sprint1.md](https://github.com/hemareddy123/ProjectK-Soen6011summer2023/compare/Himanshu's-Branch?expand=1#diffcb589da9106ed5b315b7bcc3c22be25111294767e8f7c23ae880d2ec5bb10578) file. I kindly request the reviewers to review and merge into the main branch. Also, let me know your suggestions, if any.
Thank You.

### CODE REVIEW

**Comment by himi98** [comment]
Hi Reviewers, I have resolved the merge conflict. Can you please review it again and merge into main branch? Thank You.

**Review by prafulnair — CHANGES_REQUESTED** [review]
Hey Himanshu,
I think there is some formatting issue. Kindly recheck, and add it to the latest updated file. 
Thank you.
Praful

**Review by hemareddy123 — APPROVED** [review]
looks good

**Review by prafulnair — APPROVED** [review]
Seems good now. Thanks Himanshu

**Comment by himi98** [comment]
Hi reviewers, I just resolved the merge conflict, I hope you can approve it now. Thanks.

**Pull request merged**
